---
# CI workflow for the graysmoke photo-z submission.

name: Unit test and code coverage (graysmoke)

on:
  push:
    branches: [main, graysmoke, rail+aion]
  pull_request:
    branches: [main, graysmoke, rail+aion]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
        submission: ['graysmoke']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install libbz2-dev
          python -m pip install --upgrade pip
          pip install wheel
          pip install .
          pip install .[dev]
          if [ -f requirements_${{ matrix.submission }}.txt ]; then pip install -r requirements_${{ matrix.submission }}.txt; fi
          if [ -f requirements_rail_aion.txt ]; then pip install -r requirements_rail_aion.txt; fi
      - name: Run unit tests with pytest
        env:
          XLA_PYTHON_CLIENT_PREALLOCATE: "false"
          XLA_PYTHON_CLIENT_ALLOCATOR: "platform"
          XLA_PYTHON_CLIENT_MEM_FRACTION: ".10"
          PZDC_CI_MAX_TRAIN: "500"
        run: |
          python -m pytest tests/test_${{ matrix.submission }}.py
